# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://mydomain.com'
baseurl: 'https://github.com/MPiangerelli/lignani_website/edit/master'
title: 'My website'
description: ''
permalink: pretty
logo: "unicam_logo_bianco.png"

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Progetto Lignani" # Site name or title, also used in jekyll-seo-tag
logo: "/unicam_logo_bianco.png" # Site logo, also used in jekyll-seo-tag
#description: "Computer Science Division & Math Division, Polo 'Carla Lodovici', via Madonna delle Carceri, 7" # Site description and default description, also used in jekyll-seo-tag
#url: "https://marcopiangerelli.it/" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/MPiangerelli/lignani-website.github.io"
email: "marco.piangerelli-at-unicam.it"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Methods
  url: /
- title: People
  url: /people/
#- title: Blog
#  url: /blog/

# Footer nav
#navigation_footer:
#- title: Back to top
#  url: "#top"
navigation_footer:
- title: Adapted from Alembic theme
  url: https://alembic.darn.es/

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
